import * as pulumi from "@pulumi/pulumi";
import type { NeonBranch } from "./branch";
import { NeonClient } from "./client";
import type { NeonProject } from "./project";
import type { NeonProvider } from "./provider";

/** Resolved inputs for the Neon role dynamic provider. */
export interface NeonRoleInputs {
	/** Neon API key. */
	apiKey: string;

	/** Neon project ID. */
	projectId: string;

	/** Branch ID the role belongs to. */
	branchId: string;

	/** Role name (e.g. `"neondb_owner"`). */
	name: string;

	/**
	 * When the role already exists (adopted), reset its password to a fresh value
	 * instead of revealing the inherited one. Use on copy-on-write branches to
	 * isolate the credential from the parent branch. Ignored when the role is
	 * freshly created (a new role already gets its own password).
	 */
	resetPassword: boolean;

	/**
	 * Rotation handle: bumping this number resets the role's password IN PLACE on
	 * the next `up` (an update, never a replace — replacing would try to delete
	 * the role, which Neon refuses for default roles and which would drop real
	 * grants for others). Leave unset until the first rotation is needed.
	 */
	passwordVersion?: number;
}

/** Persisted state for the Neon role. */
interface NeonRoleOutputs extends NeonRoleInputs {
	/** Role password (auto-generated by Neon). */
	password: string;
}

/** Neon API response for the reveal_password endpoint. */
interface PasswordResponse {
	password: string;
}

/** Neon API response for the reset_password endpoint (nested under `role`). */
interface ResetPasswordResponse {
	role?: { password?: string };
	password?: string;
}

/** Neon API response for listing roles. */
interface RoleListResponse {
	roles: Array<{
		name: string;
	}>;
}

/**
 * Checks if a role exists by name on a branch.
 */
async function roleExists(
	client: NeonClient,
	projectId: string,
	branchId: string,
	name: string,
): Promise<boolean> {
	const result = await client.get<RoleListResponse>(
		`/projects/${projectId}/branches/${branchId}/roles`,
	);

	return result.roles.some((r) => r.name === name);
}

/**
 * Reveals the password for an existing role via the dedicated API endpoint.
 */
async function revealPassword(
	client: NeonClient,
	projectId: string,
	branchId: string,
	name: string,
): Promise<string> {
	const result = await client.get<PasswordResponse>(
		`/projects/${projectId}/branches/${branchId}/roles/${name}/reveal_password`,
	);

	return result.password;
}

/**
 * Resets an existing role's password to a fresh value and returns it.
 * Used to isolate an adopted (copy-on-write) role from the parent branch's credential.
 */
async function resetRolePassword(
	client: NeonClient,
	projectId: string,
	branchId: string,
	name: string,
): Promise<string> {
	const result = await client.post<ResetPasswordResponse>(
		`/projects/${projectId}/branches/${branchId}/roles/${name}/reset_password`,
		{},
	);

	const password = result.role?.password ?? result.password;

	if (!password) {
		throw new Error(
			`Neon reset_password returned no password for role "${name}"`,
		);
	}

	return password;
}

/**
 * Dynamic provider implementing CRUD for Neon database roles.
 *
 * Uses adopt-or-create on `create()`: finds an existing role by name
 * before creating a new one.
 *
 * @internal Exported only for unit testing; not part of the public API surface.
 */
export class NeonRoleResourceProvider
	implements pulumi.dynamic.ResourceProvider
{
	async create(inputs: NeonRoleInputs): Promise<pulumi.dynamic.CreateResult> {
		const client = new NeonClient(inputs.apiKey);

		const exists = await roleExists(
			client,
			inputs.projectId,
			inputs.branchId,
			inputs.name,
		);

		if (!exists) {
			await client.post(
				`/projects/${inputs.projectId}/branches/${inputs.branchId}/roles`,
				{ role: { name: inputs.name } },
			);
		} else if (inputs.resetPassword) {
			pulumi.log.info(
				`Resetting password for adopted Neon role "${inputs.name}" to isolate it from the parent branch`,
			);
		} else {
			pulumi.log.info(`Adopting existing Neon role "${inputs.name}"`);
		}

		const password =
			exists && inputs.resetPassword
				? await resetRolePassword(
						client,
						inputs.projectId,
						inputs.branchId,
						inputs.name,
					)
				: await revealPassword(
						client,
						inputs.projectId,
						inputs.branchId,
						inputs.name,
					);

		return {
			id: `${inputs.branchId}/${inputs.name}`,
			outs: { ...inputs, password },
		};
	}

	async read(
		id: string,
		props: NeonRoleOutputs,
	): Promise<pulumi.dynamic.ReadResult> {
		const client = new NeonClient(props.apiKey);

		const password = await revealPassword(
			client,
			props.projectId,
			props.branchId,
			props.name,
		);

		return {
			id,
			props: { ...props, password },
		};
	}

	async delete(_id: string, props: NeonRoleOutputs): Promise<void> {
		const client = new NeonClient(props.apiKey);

		try {
			await client.delete(
				`/projects/${props.projectId}/branches/${props.branchId}/roles/${props.name}`,
			);
		} catch {
			pulumi.log.warn(
				`Failed to delete Neon role "${props.name}" (may already be deleted)`,
			);
		}
	}

	/**
	 * Rotates the password in place when `passwordVersion` changes. This is the
	 * only updatable input (everything else replaces), so an update firing means
	 * a rotation was requested.
	 */
	async update(
		id: string,
		olds: NeonRoleOutputs,
		news: NeonRoleInputs,
	): Promise<pulumi.dynamic.UpdateResult> {
		let password = olds.password;

		if (olds.passwordVersion !== news.passwordVersion) {
			pulumi.log.info(
				`Rotating password for Neon role "${news.name}" (passwordVersion ${olds.passwordVersion ?? "unset"} → ${news.passwordVersion ?? "unset"})`,
			);

			const client = new NeonClient(news.apiKey);

			password = await resetRolePassword(
				client,
				news.projectId,
				news.branchId,
				news.name,
			);
		}

		return { outs: { ...news, password } };
	}

	async diff(
		_id: string,
		olds: NeonRoleOutputs,
		news: NeonRoleInputs,
	): Promise<pulumi.dynamic.DiffResult> {
		const replaces: string[] = [];

		if (olds.projectId !== news.projectId) {
			replaces.push("projectId");
		}

		if (olds.branchId !== news.branchId) {
			replaces.push("branchId");
		}

		if (olds.name !== news.name) {
			replaces.push("name");
		}

		const rotates = olds.passwordVersion !== news.passwordVersion;

		return {
			changes: replaces.length > 0 || rotates,
			replaces,
			deleteBeforeReplace: true,
		};
	}
}

/** Internal dynamic resource — not part of the public API. */
class NeonRoleResource extends pulumi.dynamic.Resource {
	public declare readonly password: pulumi.Output<string>;

	constructor(
		name: string,
		args: {
			apiKey: pulumi.Input<string>;
			projectId: pulumi.Input<string>;
			branchId: pulumi.Input<string>;
			name: pulumi.Input<string>;
			resetPassword: pulumi.Input<boolean>;
			passwordVersion?: pulumi.Input<number>;
		},
		opts?: pulumi.CustomResourceOptions,
	) {
		// `password` is an output-only secret. Declaring it via additionalSecretOutputs
		// (rather than a pulumi.secret(undefined) input placeholder) is the only reliable
		// way to mark a dynamic-provider output secret: the placeholder gives the property
		// both a secret-undefined input and a real output, and a downstream dynamic resource
		// consuming it can race onto the undefined, producing "Unexpected struct type"
		// during protobuf serialization (Pulumi #16041, #3012).
		super(
			new NeonRoleResourceProvider(),
			name,
			{ ...args, password: undefined },
			{ ...opts, additionalSecretOutputs: ["password"] },
		);
	}
}

/** Options type for NeonRole — replaces Pulumi's native `provider` field. */
type NeonRoleOptions = Omit<pulumi.ComponentResourceOptions, "provider"> & {
	/** Neon authentication context. */
	provider: NeonProvider;

	/** Neon project context. */
	project: NeonProject;

	/** Neon branch context. */
	branch: NeonBranch;
};

/** Args for NeonRole. */
export interface NeonRoleArgs {
	/** Role name (e.g. `"neondb_owner"`). */
	name: pulumi.Input<string>;

	/**
	 * When the role is adopted (already exists on the branch), reset its password to a
	 * fresh value instead of inheriting the parent's. Set this on copy-on-write
	 * (non-production) branches to isolate the credential from production. Defaults to
	 * `false` (adopt and reveal the existing password). The reset runs once, at creation.
	 */
	resetPassword?: pulumi.Input<boolean>;

	/**
	 * Rotation handle: bump to rotate the role's password in place on the next
	 * `up`. Everything that consumes `password` (connection strings, service env
	 * vars, dependent redeploys) cascades automatically.
	 */
	passwordVersion?: pulumi.Input<number>;
}

/**
 * Manages a Neon database role with adopt-or-create semantics.
 * Exposes `password` as a secret output for connection string composition.
 *
 * @example
 * ```typescript
 * const role = new NeonRole("owner", {
 *   name: "neondb_owner",
 * }, { provider, project, branch });
 * ```
 */
export class NeonRole extends pulumi.ComponentResource {
	/** Role password (secret). */
	public readonly password: pulumi.Output<string>;

	constructor(name: string, args: NeonRoleArgs, opts: NeonRoleOptions) {
		const { provider, project, branch, ...pulumiOpts } = opts;

		super("infracraft:neon:Role", name, {}, pulumiOpts);

		const resource = new NeonRoleResource(
			`${name}-resource`,
			{
				apiKey: provider.apiKey,
				projectId: project.id,
				branchId: branch.id,
				name: args.name,
				resetPassword: args.resetPassword ?? false,
				passwordVersion: args.passwordVersion,
			},
			{ parent: this },
		);

		this.password = resource.password;

		this.registerOutputs({ password: this.password });
	}
}
