import * as pulumi from "@pulumi/pulumi";
import { NeonClient } from "./client.js";

/** Resolved inputs for the Neon role dynamic provider. */
export interface NeonRoleInputs {
	/** Neon API key. */
	apiKey: string;

	/** Neon project ID. */
	projectId: string;

	/** Branch ID the role belongs to. */
	branchId: string;

	/** Role name (e.g. `"neondb_owner"`). */
	name: string;
}

/** Persisted state for the Neon role. */
interface NeonRoleOutputs extends NeonRoleInputs {
	/** Role password (auto-generated by Neon). */
	password: string;
}

/** Neon API response for the reveal_password endpoint. */
interface PasswordResponse {
	password: string;
}

/** Neon API response for listing roles. */
interface RoleListResponse {
	roles: Array<{
		name: string;
	}>;
}

/**
 * Checks if a role exists by name on a branch.
 *
 * @param client Authenticated Neon API client
 * @param projectId Neon project ID
 * @param branchId Branch ID to search within
 * @param name Exact role name to match
 * @returns `true` if found, `false` otherwise
 */
async function roleExists(
	client: NeonClient,
	projectId: string,
	branchId: string,
	name: string,
): Promise<boolean> {
	const result = await client.get<RoleListResponse>(
		`/projects/${projectId}/branches/${branchId}/roles`,
	);

	return result.roles.some((r) => r.name === name);
}

/**
 * Reveals the password for an existing role via the dedicated API endpoint.
 *
 * @param client Authenticated Neon API client
 * @param projectId Neon project ID
 * @param branchId Branch ID
 * @param name Role name
 * @returns The role password
 */
async function revealPassword(
	client: NeonClient,
	projectId: string,
	branchId: string,
	name: string,
): Promise<string> {
	const result = await client.get<PasswordResponse>(
		`/projects/${projectId}/branches/${branchId}/roles/${name}/reveal_password`,
	);

	return result.password;
}

/**
 * Dynamic provider implementing CRUD for Neon database roles.
 *
 * Uses adopt-or-create on `create()`: finds an existing role by name
 * before creating a new one.
 */
class NeonRoleProvider implements pulumi.dynamic.ResourceProvider {
	/**
	 * Creates or adopts a Neon role by name.
	 *
	 * @param inputs Resolved role configuration
	 * @returns Composite ID `{branchId}/{roleName}` as the resource ID
	 */
	async create(inputs: NeonRoleInputs): Promise<pulumi.dynamic.CreateResult> {
		const client = new NeonClient(inputs.apiKey);

		const exists = await roleExists(
			client,
			inputs.projectId,
			inputs.branchId,
			inputs.name,
		);

		if (!exists) {
			await client.post(
				`/projects/${inputs.projectId}/branches/${inputs.branchId}/roles`,
				{ role: { name: inputs.name } },
			);
		} else {
			pulumi.log.info(`Adopting existing Neon role "${inputs.name}"`);
		}

		const password = await revealPassword(
			client,
			inputs.projectId,
			inputs.branchId,
			inputs.name,
		);

		return {
			id: `${inputs.branchId}/${inputs.name}`,
			outs: { ...inputs, password },
		};
	}

	/**
	 * Reads current state for `pulumi refresh`.
	 *
	 * @param id Current composite role ID
	 * @param props Last known persisted state
	 * @returns Refreshed resource ID and properties with current password
	 * @throws {Error} If the role no longer exists
	 */
	async read(
		id: string,
		props: NeonRoleOutputs,
	): Promise<pulumi.dynamic.ReadResult> {
		const client = new NeonClient(props.apiKey);

		const password = await revealPassword(
			client,
			props.projectId,
			props.branchId,
			props.name,
		);

		return {
			id,
			props: { ...props, password },
		};
	}

	/**
	 * Deletes the Neon role. Silently succeeds if already deleted.
	 */
	async delete(_id: string, props: NeonRoleOutputs): Promise<void> {
		const client = new NeonClient(props.apiKey);

		try {
			await client.delete(
				`/projects/${props.projectId}/branches/${props.branchId}/roles/${props.name}`,
			);
		} catch {
			pulumi.log.warn(
				`Failed to delete Neon role "${props.name}" (may already be deleted)`,
			);
		}
	}

	/**
	 * Compares old and new inputs. Changing any field triggers replacement
	 * since roles cannot be renamed or moved between branches.
	 */
	async diff(
		_id: string,
		olds: NeonRoleOutputs,
		news: NeonRoleInputs,
	): Promise<pulumi.dynamic.DiffResult> {
		const replaces: string[] = [];

		if (olds.projectId !== news.projectId) {
			replaces.push("projectId");
		}

		if (olds.branchId !== news.branchId) {
			replaces.push("branchId");
		}

		if (olds.name !== news.name) {
			replaces.push("name");
		}

		return {
			changes: replaces.length > 0,
			replaces,
			deleteBeforeReplace: true,
		};
	}
}

/**
 * Manages a Neon database role with adopt-or-create semantics.
 * Exposes `password` as a secret output for connection string composition.
 *
 * @example
 * ```typescript
 * const role = new NeonRole("neon-role-owner", {
 *   apiKey: config.requireSecret("neonApiKey"),
 *   projectId: "quiet-forest-69719462",
 *   branchId: branch.id,
 *   name: "neondb_owner",
 * });
 *
 * const password = role.password;
 * ```
 */
export class NeonRole extends pulumi.dynamic.Resource {
	/** Role password (auto-generated by Neon). */
	public declare readonly password: pulumi.Output<string>;

	/**
	 * @param name Pulumi resource name
	 * @param args Role configuration inputs
	 * @param opts Standard Pulumi resource options
	 */
	constructor(
		name: string,
		args: {
			/** Neon API key. */
			apiKey: pulumi.Input<string>;

			/** Neon project ID. */
			projectId: pulumi.Input<string>;

			/** Branch ID the role belongs to. */
			branchId: pulumi.Input<string>;

			/** Role name (e.g. `"neondb_owner"`). */
			name: pulumi.Input<string>;
		},
		opts?: pulumi.CustomResourceOptions,
	) {
		super(new NeonRoleProvider(), name, { ...args, password: undefined }, opts);
	}
}
