import * as pulumi from "@pulumi/pulumi";
import { NeonClient } from "./client.js";
import type { NeonBranch } from "./branch.js";
import type { NeonProject } from "./project.js";
import type { NeonProvider } from "./provider.js";

/** Resolved inputs for the Neon role dynamic provider. */
export interface NeonRoleInputs {
	/** Neon API key. */
	apiKey: string;

	/** Neon project ID. */
	projectId: string;

	/** Branch ID the role belongs to. */
	branchId: string;

	/** Role name (e.g. `"neondb_owner"`). */
	name: string;
}

/** Persisted state for the Neon role. */
interface NeonRoleOutputs extends NeonRoleInputs {
	/** Role password (auto-generated by Neon). */
	password: string;
}

/** Neon API response for the reveal_password endpoint. */
interface PasswordResponse {
	password: string;
}

/** Neon API response for listing roles. */
interface RoleListResponse {
	roles: Array<{
		name: string;
	}>;
}

/**
 * Checks if a role exists by name on a branch.
 */
async function roleExists(
	client: NeonClient,
	projectId: string,
	branchId: string,
	name: string,
): Promise<boolean> {
	const result = await client.get<RoleListResponse>(
		`/projects/${projectId}/branches/${branchId}/roles`,
	);

	return result.roles.some((r) => r.name === name);
}

/**
 * Reveals the password for an existing role via the dedicated API endpoint.
 */
async function revealPassword(
	client: NeonClient,
	projectId: string,
	branchId: string,
	name: string,
): Promise<string> {
	const result = await client.get<PasswordResponse>(
		`/projects/${projectId}/branches/${branchId}/roles/${name}/reveal_password`,
	);

	return result.password;
}

/**
 * Dynamic provider implementing CRUD for Neon database roles.
 *
 * Uses adopt-or-create on `create()`: finds an existing role by name
 * before creating a new one.
 */
class NeonRoleResourceProvider implements pulumi.dynamic.ResourceProvider {
	async create(inputs: NeonRoleInputs): Promise<pulumi.dynamic.CreateResult> {
		const client = new NeonClient(inputs.apiKey);

		const exists = await roleExists(
			client,
			inputs.projectId,
			inputs.branchId,
			inputs.name,
		);

		if (!exists) {
			await client.post(
				`/projects/${inputs.projectId}/branches/${inputs.branchId}/roles`,
				{ role: { name: inputs.name } },
			);
		} else {
			pulumi.log.info(`Adopting existing Neon role "${inputs.name}"`);
		}

		const password = await revealPassword(
			client,
			inputs.projectId,
			inputs.branchId,
			inputs.name,
		);

		return {
			id: `${inputs.branchId}/${inputs.name}`,
			outs: { ...inputs, password },
		};
	}

	async read(
		id: string,
		props: NeonRoleOutputs,
	): Promise<pulumi.dynamic.ReadResult> {
		const client = new NeonClient(props.apiKey);

		const password = await revealPassword(
			client,
			props.projectId,
			props.branchId,
			props.name,
		);

		return {
			id,
			props: { ...props, password },
		};
	}

	async delete(_id: string, props: NeonRoleOutputs): Promise<void> {
		const client = new NeonClient(props.apiKey);

		try {
			await client.delete(
				`/projects/${props.projectId}/branches/${props.branchId}/roles/${props.name}`,
			);
		} catch {
			pulumi.log.warn(
				`Failed to delete Neon role "${props.name}" (may already be deleted)`,
			);
		}
	}

	async diff(
		_id: string,
		olds: NeonRoleOutputs,
		news: NeonRoleInputs,
	): Promise<pulumi.dynamic.DiffResult> {
		const replaces: string[] = [];

		if (olds.projectId !== news.projectId) {
			replaces.push("projectId");
		}

		if (olds.branchId !== news.branchId) {
			replaces.push("branchId");
		}

		if (olds.name !== news.name) {
			replaces.push("name");
		}

		return {
			changes: replaces.length > 0,
			replaces,
			deleteBeforeReplace: true,
		};
	}
}

/** Internal dynamic resource — not part of the public API. */
class NeonRoleResource extends pulumi.dynamic.Resource {
	public declare readonly password: pulumi.Output<string>;

	constructor(
		name: string,
		args: {
			apiKey: pulumi.Input<string>;
			projectId: pulumi.Input<string>;
			branchId: pulumi.Input<string>;
			name: pulumi.Input<string>;
		},
		opts?: pulumi.CustomResourceOptions,
	) {
		super(
			new NeonRoleResourceProvider(),
			name,
			{ ...args, password: pulumi.secret(undefined as unknown as string) },
			opts,
		);
	}
}

/** Options type for NeonRole — replaces Pulumi's native `provider` field. */
type NeonRoleOptions = Omit<pulumi.ComponentResourceOptions, "provider"> & {
	/** Neon authentication context. */
	provider: NeonProvider;

	/** Neon project context. */
	project: NeonProject;

	/** Neon branch context. */
	branch: NeonBranch;
};

/** Args for NeonRole. */
export interface NeonRoleArgs {
	/** Role name (e.g. `"neondb_owner"`). */
	name: pulumi.Input<string>;
}

/**
 * Manages a Neon database role with adopt-or-create semantics.
 * Exposes `password` as a secret output for connection string composition.
 *
 * @example
 * ```typescript
 * const role = new NeonRole("owner", {
 *   name: "neondb_owner",
 * }, { provider, project, branch });
 * ```
 */
export class NeonRole extends pulumi.ComponentResource {
	/** Role password (secret). */
	public readonly password: pulumi.Output<string>;

	constructor(
		name: string,
		args: NeonRoleArgs,
		opts: NeonRoleOptions,
	) {
		const { provider, project, branch, ...pulumiOpts } = opts;

		super("infracraft:neon:Role", name, {}, pulumiOpts);

		const resource = new NeonRoleResource(
			`${name}-resource`,
			{
				apiKey: provider.apiKey,
				projectId: project.projectId,
				branchId: branch.branchId,
				name: args.name,
			},
			{ parent: this },
		);

		this.password = resource.password;

		this.registerOutputs({ password: this.password });
	}
}
